### PR TITLE
chore: add angular template link to issue templates

### PR DESCRIPTION
**Pull request by DitwanP**
**Related Issue:** #8567

## Summary
Add a link to the bug and a11y issue templates for this [codesandbox](https://codesandbox.io/p/sandbox/little-fire-2hx4qh?file=%2Fsrc%2Fapp%2Fapp.component.html%3A16%2C51) that I created as a calcite components angular template.

### CODE REVIEW

**Review by alisonailea — APPROVED** [review]

**Review by geospatialem — COMMENTED** [review]
Awesome updates! 🧰 

WRT the Codesandbox Angular sample, WDYT about the following considerations?:
1. Adding a [NgIf directive](https://angular.io/api/common/NgIf) to conditionally display content similar to our [Angular example](https://github.com/Esri/calcite-components-examples/blob/main/angular/src/app/app.component.html#L1) in `calcite-components-examples`?
2. Adding a [template variable](https://angular.io/guide/template-reference-variables), also similar to our [Angular example](https://github.com/Esri/calcite-components-examples/blob/main/angular/src/app/app.component.html#L5) in `calcite-components-examples`?

Both are used fairly regular in Angular, so could be good considerations for the template to get folks started.

**Comment by DitwanP** [comment]
> Awesome updates! 🧰
> 
> WRT the Codesandbox Angular sample, WDYT about the following considerations?:
> 
> 1. Adding a [NgIf directive](https://angular.io/api/common/NgIf) to conditionally display content similar to our [Angular example](https://github.com/Esri/calcite-components-examples/blob/main/angular/src/app/app.component.html#L1) in `calcite-components-examples`?
> 2. Adding a [template variable](https://angular.io/guide/template-reference-variables), also similar to our [Angular example](https://github.com/Esri/calcite-components-examples/blob/main/angular/src/app/app.component.html#L5) in `calcite-components-examples`?
> 
> Both are used fairly regular in Angular, so could be good considerations for the template to get folks started.

Yeah that makes sense, I'll get that in there.

**Review by geospatialem — APPROVED** [review]
LGTM 🌟🚀🌟

**Review by benelan — APPROVED** [review]
Nice, thanks for adding this! A couple minor notes:

- You can remove the `@esri/calcite-components` dependency since it is included with `@esri/calcite-components-angular`

- You should be able to remove all of these `jasmine` and `karma` deps since there aren't any tests in the sample. Doing so might make the app load faster

  ```json
  "devDependencies": {
      "@types/jasmine": "3.6.3",
      "@types/jasminewd2": "2.0.8",
      "jasmine-core": "3.6.0",
      "jasmine-spec-reporter": "6.0.0",
      "karma": "6.1.1",
      "karma-chrome-launcher": "3.1.0",
      "karma-coverage-istanbul-reporter": "3.0.3",
      "karma-jasmine": "4.0.1",
      "karma-jasmine-html-reporter": "1.5.4"
    }
  ```

- We may want to use the jsdelivr or unpkg CDN for the assets like the React sample does so we don't need to update the
  hardcoded version after every release.

  ```js
  defineCustomElements(window, {
    resourcesUrl: "https://cdn.jsdelivr.net/npm/@esri/calcite-components@latest/dist/calcite/assets",
  });
  ```

**Comment by DitwanP** [comment]
@benelan Great suggestions! I'll make those adjustments, thank you.

**Pull request merged**
