### PR TITLE
refactor(storybook): replace fake knobs with controls for simple stories

### PR DESCRIPTION
**Pull request by aPreciado88**
**Related Issue:** [9084](https://github.com/Esri/calcite-design-system/issues/9084)

## Summary 
-Replaces knobs with controls for `simple` stories.
-Removes knobs used in all other stories.
-Replaces usage of `createComponentHTML` and related utils with HTML.

### CODE REVIEW

**Review by jcfranco — CHANGES_REQUESTED** [review]
This looks great, @aPreciado88! 🤘😎🤘

The main thing that needs to be addressed is the update to `packages/calcite-components/src/components/interfaces.ts` affecting component APIs. The rest can be tackled in follow-up PRs.

**Review by jcfranco — APPROVED** [review]
Awesome! Thanks for moving the interface changes to the Storybook folder. 

The rest of my previous comments can be tackled in follow-up PRs, so I'll approve and leave it up to you.

Before merging, can you:

* resolve merge conflicts
* add the `ready for visual snapshots` label to run screenshot tests
* create a follow-up issue to consolidate the storybook & component types

?

**Comment by aPreciado88** [comment]
@jcfranco Thank you for approving it! I'm going through your other comments and trying to get as much as I can in, so it can go out next week. I'll create follow-up issues for the remaining work, as you suggested.

**Comment by aPreciado88** [comment]
@ashetland @SkyeSeitz Could you please give this a review?

**Comment by ashetland** [comment]
Controls are looking good to me!

**Pull request merged**
