### PR TITLE
fix(list-item): Always reserve spacing for open icon

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #8667

## Summary

- Always reserve space for open toggle icon
- Screenshot tests show changes

### CODE REVIEW

**Comment by ashetland** [comment]
I just noticed that the "Nested List" page isn't expanded in the baseline or new so chromatic isn't showing the changes. It might be worth expanding all the items in that page so we have it as a baseline.

**Comment by ashetland** [comment]
Also the baseline is showing the old icons?
CleanShot 2024-01-30 at 11 02 14@2x

**Comment by driskull** [comment]
I think those icons are slotted in, not in the component

**Review by alisonailea — APPROVED** [review]

**Comment by driskull** [comment]
@ashetland is this one good to merge?

**Comment by ashetland** [comment]
Sadly no. We got feedback that folks aren't super happy about the added space in a flat list scenario. I'm drawing up specs for revised spacing in both flat and nested lists as there was a strong desire for this to be configurable. We'll need to push implementation to March. cc @jcfranco

**Comment by driskull** [comment]
> there was a strong desire for this to be configurable

I think that would be a breaking change if we required people to configure allowing nesting and doesn't seem very user friendly to have to do.

If the reserved space for a nesting icon is an issue maybe it should be moved to the opposite side like the block/accordion components?

**Pull request closed without merging**
