### PR TITLE
refactor: migrate to style dictionary v4

### PR DESCRIPTION
**Pull request by AkshitGarg24**
## Proposed Changes

This PR introduces a codemod that automates the migration to Style Dictionary 4 by transforming configuration files, formats, and other breaking changes from previous versions, as described in the [Style Dictionary v4 migration guide](https://v4.styledictionary.com/version-4/migration/).

You can test/run the codemod using:

```
npx codemod styledictionary/4/migration-recipe
```

This allows users of earlier versions of Style Dictionary to easily automate the migration to version 4 with a single command. By leveraging the Codemod CLI, users can take advantage of a seamless migration experience similar to that offered by other popular frameworks like [React](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#codemods), [Nuxt.js](https://nuxt.com/docs/getting-started/upgrade#migrating-using-codemods), and [pnpm](https://pnpm.io/catalogs#defining-catalogs).

This codemod is a step towards simplifying the Style Dictionary v4 upgrade process. If this PR is well-received, our community is eager to contribute more codemods to further automate and streamline the migration path for Style Dictionary users.

### CODE REVIEW

**Review by jcfranco — CHANGES_REQUESTED** [review]
Thanks for the contribution, @AkshitGarg24! 

Before reviewing and testing, would you mind scoping the codemod changes to the `calcite-design-tokens` package and updating the PR title to follow [our conventions](https://github.com/Esri/calcite-design-system/blob/main/CONTRIBUTING.md#contribution-example)? LMK if you have any questions.

**Comment by AkshitGarg24** [comment]
Hello @jcfranco,

I have made the required changes. Please let me know if there are any additional modifications needed or if I missed anything.

**Comment by AkshitGarg24** [comment]
Hello @jcfranco,

I have made the required changes. Please let me know if there are any additional modifications needed or if I missed anything.

**Comment by jcfranco** [comment]
@AkshitGarg24 Were you been able to get a successful build locally? I haven't had luck and suspect we'll need additional changes to our package before migrating.

**Comment by jcfranco** [comment]
@AkshitGarg24 Thanks again for the PR! Since some items are still pending and there haven’t been any recent updates, I’ll close it for now. We can revisit migrating at a later point.

**Pull request closed without merging**
