### PR TITLE
fix(combobox): fix issue causing value to be cleared when selecting an item (Windows + trackpad)

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #7934 

## Summary

Updates the component to consistently bail on blur handling logic if the input is blurred, but focus is still within the component.

### Notes

* the regression was introduced by https://github.com/Esri/calcite-design-system/pull/7721/
* due to time constraints, testing will be tackled in a follow-up issue as it's not easy to reproduce in an E2E test.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
Awesome! 🌈 ☁️ 🦄

**Comment by jcfranco** [comment]
@anveshmekala Could you give this a look and comment if you notice anything I may have missed?

**Comment by anveshmekala** [comment]
> @anveshmekala Could you give this a look and comment if you notice anything I may have missed?

This will break the issue #[2162](https://github.com/Esri/calcite-design-system/issues/2162) when the user chooses to enter some custom value and tab  out of the component. The tests should have cover this scenario but they are validating against the value property which will be empty since there are no `selectedItems`.

**Comment by jcfranco** [comment]
Yikes, thanks for catching that! I knew this fix felt too easy. 😂

**Pull request merged**
