### PR TITLE
revert(tile-group): add responsive Tile Group component (#8687)

### PR DESCRIPTION
**Pull request by alisonailea**
## Summary

This reverts commit bf0c906a26bf763e6745dc97da223c7592f7fef1.

### CODE REVIEW

**Comment by driskull** [comment]
Hey @alisonailea whats the reason to revert this? Shouldn't we just leave it alone if we don't want to tokenize it yet.

**Comment by alisonailea** [comment]
> Hey @alisonailea whats the reason to revert this? Shouldn't we just leave it alone if we don't want to tokenize it yet.

This was merged accidently to the epic branch when it should have gone to main

**Review by driskull — APPROVED** [review]

**Comment by jcfranco** [comment]
This can stay as is. https://github.com/Esri/calcite-design-system/pull/8806 is landing on `main` soon and we'll merge that onto this branch.

**Comment by jcfranco** [comment]
Merged and epic branch updated! 🚀 Closing!

**Pull request closed without merging**
