### PR TITLE
ci(release-please): use default pull request title

### PR DESCRIPTION
**Pull request by benelan**
## Summary

`release-please` was having problems finding it's own pull requests, which was causing issues with the post-merge deployments. The [logs say the problem is with the custom pull request title](https://github.com/Esri/calcite-design-system/actions/runs/5756030451/job/15604709660#step:2:28). Reverting the configuration to the default title seemed to fix the issues in my test repo.

### CODE REVIEW

**Review by driskull — APPROVED** [review]

**Comment by jcfranco** [comment]
What does the default PR title look like?

**Comment by benelan** [comment]
> What does the default PR title look like?

`chore: release main`

I think release-please needs the branch name in the PR title for some reason, because changing it to `chore: release latest` broke stuff lol

**Comment by benelan** [comment]
@jcfranco I'm installing this, but we should be able to change the commit message when merging if you'd prefer `chore: release latest`. I'll check on my test repo before the next release

**Comment by jcfranco** [comment]
[Belated] Sounds good. Thanks! 🚀

**Pull request merged**
