### PR TITLE
fix: replace "\n" to support Windows for tokens output

### PR DESCRIPTION
**Pull request by alisonailea**
**Related Issue:** #8350

## Summary

Fixes an issue that was causing problems in Windows by handing off control of formatting to the experts and by experts I mean Prettier.

### CODE REVIEW

**Review by benelan — COMMENTED** [review]
Awesome, this looks a lot cleaner! Has Kitty tested on this branch? We should make sure there aren't other Windows issues before we say it supports Windows.

**Review by jcfranco — APPROVED** [review]
Noice! ✨💅✨

**Review by geospatialem — COMMENTED** [review]
Tested locally in a new clone on Windows. Perhaps unrelated to the `\n` use, but still running into issues with Windows WRT to the `--calcite-modal-scrim-background` variable. @alisonailea Do we need a new issue to track the effort?

image

image (1)

**Comment by alisonailea** [comment]
> Tested locally in a new clone on Windows. Perhaps unrelated to the `\n` use, but still running into issues with Windows WRT to the `--calcite-modal-scrim-background` variable. @alisonailea Do we need a new issue to track the effort?
> 

Thanks for catching this. Weird that none of the other tests threw an error here.

**Review by geospatialem — APPROVED** [review]
🎉 🏆 🎉 

Windows is up and running again! Nice work, @alisonailea! 🥇

**Pull request merged**
