### PR TITLE
fix: set the correct Sortable parent when within a shadowRoot

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #9521

## Summary

- patch sortablejs with the correct update to fix dragging shadow elements on mobile devices
- https://github.com/SortableJS/Sortable/pull/2347 https://github.com/SortableJS/Sortable/issues/2346

### CODE REVIEW

**Comment by driskull** [comment]
@jcfranco can we do this one for June release?

**Review by jcfranco — APPROVED** [review]
LGTM!

It looks like the related issue has been closed and verified already. Should we reopen and bounce back or do we need to create a new issue? +@geospatialem for guidance.

**Comment by driskull** [comment]
> It looks like the related issue has been closed and verified already. Should we reopen and bounce back or do we need to create a new issue

Yeah, we did fix the issue but we didn't do it the correct way according to Sortablejs. So we can reopen or create a new issue .

**Comment by geospatialem** [comment]
> Yeah, we did fix the issue but we didn't do it the correct way according to Sortablejs. So we can reopen or create a new issue.

Ah, good to know - I'll re-open the issue.

**Pull request merged**
