### PR TITLE
feat(list-item-group): update list item group styles

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #8039

## Summary

- update list item group styles
- updates internal table cell classes to remove padding being set by default browser styles.

### CODE REVIEW

**Comment by driskull** [comment]
@ashetland can you review these changes?

**Comment by jcfranco** [comment]
@driskull The linked issue is for an enhancement, so should this use `feat`? Also, do we need to use the `visual changes` label? It looks like spacing was tweaked a bit.

**Comment by driskull** [comment]
Yeah that makes sense. 👍

**Comment by driskull** [comment]
@ashetland can you review?

**Comment by ashetland** [comment]
Lookin gewd!

**Pull request merged**
