### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by calcite-admin**
:robot: I have created a release *beep* *boop*
---

<details><summary>@esri/calcite-design-tokens: 2.1.2</summary>

### Bug Fixes

* Fix invalid font stacks ([#8964](https://github.com/Esri/calcite-design-system/issues/8964)) ([d55186a](https://github.com/Esri/calcite-design-system/commit/d55186abe6d4011fdfd357c3c15aa9638e25927d))
</details>

<details><summary>@esri/calcite-components: 2.7.0</summary>

### Features

* **button:** Add download property ([#8882](https://github.com/Esri/calcite-design-system/issues/8882)) ([fc55dde](https://github.com/Esri/calcite-design-system/commit/fc55dde3e4be2e846181f77d95e9eb8f0c0f90b0))
* **color-picker:** Add `clearable` prop and deprecate `allowEmpty` ([#8910](https://github.com/Esri/calcite-design-system/issues/8910)) ([f036ac2](https://github.com/Esri/calcite-design-system/commit/f036ac27bc8f361c03e3a7001d8d3fdbf4af04f6))
* **table-row:** Add alignment property ([#8961](https://github.com/Esri/calcite-design-system/issues/8961)) ([1f81fd7](https://github.com/Esri/calcite-design-system/commit/1f81fd713f9780d63bb4820256c038f4cdc13a32))
* **tabs:** Make component responsive ([#8616](https://github.com/Esri/calcite-design-system/issues/8616)) ([83a2ef4](https://github.com/Esri/calcite-design-system/commit/83a2ef47157f88007af0ae528758fb5952a3f3bc))
* **tile:** Add content-top and content-bottom slots, deprecate content-start and content-end slots ([#8984](https://github.com/Esri/calcite-design-system/issues/8984)) ([eb000d8](https://github.com/Esri/calcite-design-system/commit/eb000d844856695ab1c76031128f872ecf7f4797))

### Bug Fixes

* **action-menu, combobox, dropdown, popover, tooltip:** Use click instead of pointerdown for click contexts ([#8943](https://github.com/Esri/calcite-design-system/issues/8943)) ([cd7eed9](https://github.com/Esri/calcite-design-system/commit/cd7eed97282d2686c07d46ccd658956c8e4a138f))
* **card:** Do not apply text color to slotted footer items ([#8839](https://github.com/Esri/calcite-design-system/issues/8839)) ([30a2068](https://github.com/Esri/calcite-design-system/commit/30a206867d5f4b19d9cdfcc540f0286405b6d984))
* **combobox:** Prevent spacebar from opening the menu when focused on chip's close button ([#8990](https://github.com/Esri/calcite-design-system/issues/8990)) ([1a20d0e](https://github.com/Esri/calcite-design-system/commit/1a20d0eb740dbe2e371aeff90b8b9f301ca8bf2a))
* **dropdown:** Correct positioning behavior when inside a scrollable container ([#8973](https://github.com/Esri/calcite-design-system/issues/8973)) ([2524391](https://github.com/Esri/calcite-design-system/commit/2524391064327ff54e01164dc352e3acbc3459d3))
* **input-time-picker:** Update toggle icon color ([#8955](https://github.com/Esri/calcite-design-system/issues/8955)) ([ce3ac5c](https://github.com/Esri/calcite-design-system/commit/ce3ac5cc514536c66dde9b26542a24c62e193b11))
* **input, input-number, input-text:** Ensure values are initialized properly for dist and components output targets ([#8997](https://github.com/Esri/calcite-design-system/issues/8997)) ([9152211](https://github.com/Esri/calcite-design-system/commit/915221146fcb1f48115fd34726324535542321df))
* **list, list-item:** Calcite-select becomes unresponsive in a list-item if drag-disabled is true ([#8957](https://github.com/Esri/calcite-design-system/issues/8957)) ([e408c62](https://github.com/Esri/calcite-design-system/commit/e408c626429ce60e0c21b23720ba42b490cabec7))
* **list:** Fix filter box when scrolling in Safari ([#8938](https://github.com/Esri/calcite-design-system/issues/8938)) ([ea8ea1e](https://github.com/Esri/calcite-design-system/commit/ea8ea1e3795dbc8d92a064fad8ebc00d13383252))
* **popover:** Prevent disabled reference elements from toggling popover ([#8983](https://github.com/Esri/calcite-design-system/issues/8983)) ([9f4b14b](https://github.com/Esri/calcite-design-system/commit/9f4b14bd8218d0457a4943f583c1d81aa6d84e1f))
* **stepper:** Fix layout when switching modes dynamically to `horizontal-single` ([#8946](https://github.com/Esri/calcite-design-system/issues/8946)) ([01f58bf](https://github.com/Esri/calcite-design-system/commit/01f58bff05ac43777342df4a5d77804bf4c3677c))
* **table:** Prevent duplicate scrollbars in certain browsers ([#8962](https://github.com/Esri/calcite-design-system/issues/8962)) ([8434eeb](https://github.com/Esri/calcite-design-system/commit/8434eeb3fa94144066c9b59b77f5d0487c05588c))
* **tab:** Style focus outline of tab content ([#8804](https://github.com/Esri/calcite-design-system/issues/8804)) ([8f0133f](https://github.com/Esri/calcite-design-system/commit/8f0133fbd5f54493a7bb848a4b9f7ebde3c8eb61))

### Performance Improvements

* Update `transition-default` Tailwind util to only target common, animatable properties ([#8797](https://github.com/Esri/calcite-design-system/issues/8797)) ([f4d016b](https://github.com/Esri/calcite-design-system/commit/f4d016b0998f360f376c03705c98bd6c399143f6))

### Reverts

* Refactor(popover): update token pattern ([#8889](https://github.com/Esri/calcite-design-system/issues/8889)) ([c43c280](https://github.com/Esri/calcite-design-system/commit/c43c280787d15e5602b2c9e13d01b0ebe2492901))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @esri/calcite-design-tokens bumped from ^2.1.2-next.2 to ^2.1.2
</details>

<details><summary>@esri/calcite-components-angular: 2.7.0</summary>

### Miscellaneous Chores

* **@esri/calcite-components-angular:** Synchronize components versions

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @esri/calcite-components bumped from ^2.7.0-next.17 to ^2.7.0
</details>

<details><summary>@esri/calcite-components-react: 2.7.0</summary>

### Miscellaneous Chores

* **@esri/calcite-components-react:** Synchronize components versions

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @esri/calcite-components bumped from ^2.7.0-next.17 to ^2.7.0
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by geospatialem — APPROVED** [review]
🌟 🚀 🌟

**Comment by calcite-admin** [comment]
:robot: Release is at https://github.com/Esri/calcite-design-system/releases/tag/%40esri/calcite-components%402.7.0 :sunflower:

**Comment by calcite-admin** [comment]
:robot: Release is at https://github.com/Esri/calcite-design-system/releases/tag/%40esri/calcite-components-react%402.7.0 :sunflower:

**Comment by calcite-admin** [comment]
:robot: Release is at https://github.com/Esri/calcite-design-system/releases/tag/%40esri/calcite-components-angular%402.7.0 :sunflower:

**Comment by calcite-admin** [comment]
:robot: Release is at https://github.com/Esri/calcite-design-system/releases/tag/%40esri/calcite-design-tokens%402.1.2 :sunflower:

**Pull request merged**
