### PR TITLE
refactor(card)!: remove deprecated `deselected` message

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #6660

## Summary

BREAKING CHANGE: Removed the `deselect` message property – this property was deprecated in #6657 as it is no longer being rendered.

### CODE REVIEW

**Review by benelan — APPROVED** [review]
Nitpick: I think starting the breaking change notice with a verb sounds better, e.g.

> BREAKING CHANGE: Remove the \`deselect\` message property, which was deprecated in #6657 and is not being rendered.

**Comment by jcfranco** [comment]
@benelan Revised!

**Comment by jcfranco** [comment]
@benelan Can you give this another look? I updated the `translations-json.json` generating script to handle removed messages.

**Review by benelan — CHANGES_REQUESTED** [review]
The script change LGTM! Thanks for doing that - the other README related issue you brought up is still on my list lol.

However, can you recreate this PR targeting the `rc` branch once #8122 is installed?

**Comment by jcfranco** [comment]
> However, can you recreate this PR targeting the `rc` branch once #8122 is installed?

I ended up changing this PR’s base branch.

**Review by benelan — APPROVED** [review]
> I ended up changing this PR’s base branch.

TIL you can do that lol

**Pull request merged**
