### PR TITLE
fix: use Stencil watchers instead of global attributes util

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #8193 

## Summary

Stencil v4 allows [watching global attributes](https://stenciljs.com/docs/reactive-data#watching-native-html-attributes) on components, so we no longer need our custom util for this.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
This is awesome 💯 

Nice work 👍

**Review by anveshmekala — APPROVED** [review]
🥇

**Comment by anveshmekala** [comment]
Chromatic changes looks unrelated to the PR.

**Comment by eriklharper** [comment]
Great milestone!  We've been waiting for this for years :)

**Pull request merged**
