### PR TITLE
fix(stepper-item): update component to take full width when parent's layout is "vertical"

### PR DESCRIPTION
**Pull request by aPreciado88**
**Related Issue:** [#8930](https://github.com/Esri/calcite-design-system/issues/8930)

## Summary
Update `stepper-item` to take full width when parent `stepper`'s layout is "vertical".

### CODE REVIEW

**Review by driskull — COMMENTED** [review]
Code changes look good, but it needs a screenshot test in order to cover this functionality. Can you add a screenshot story for this?

**Comment by aPreciado88** [comment]
@driskull I added a screenshot test 🚀

**Review by driskull — APPROVED** [review]
👍

**Comment by aPreciado88** [comment]
@ashetland @SkyeSeitz Could you please take a look at the new stepper snapshot, and approve if it looks correct?

**Pull request merged**
