### PR TITLE
fix(tabs): Update tab title indicator display

### PR DESCRIPTION
**Pull request by macandcheese**
**Related Issue:** #8800, #8772 

## Summary

Removes the previous selection indicator behavior and moves the styling to the Tab Title component itself. Removes associated stale code and tests. Small visual tweaks to resolve alignment and spacing issues.

### CODE REVIEW

**Comment by jcfranco** [comment]
> ## Summary
> 
> *WIP*
> 
> Removes...

Is this still WIP?

**Comment by macandcheese** [comment]
> > ## Summary
> > _WIP_
> > Removes...
> 
> Is this still WIP?

Whoops, yeah.

**Review by driskull — APPROVED** [review]
LGTM! 🎉

**Comment by ashetland** [comment]
🚀

**Review by ashetland — APPROVED** [review]
🚀🚀🚀 Looks great!

**Pull request merged**
