### PR TITLE
chore: remove component usage files

### PR DESCRIPTION
**Pull request by DitwanP**
**Related Issue:** #9015 

## Summary
Removing usage sample files from repo since we now have links to each components page on the doc site for more in depth information and samples.

### CODE REVIEW

**Comment by driskull** [comment]
I'm not sure I agree with removing these at this time.

@jcfranco what about where we are lacking coverage for some of these on the doc site? For example, there is no virtual element info on popover in the doc site.

If we remove some of these usage files I'm concerned we will be losing info on how to do some things. 

IMO it would be better to leave these until we can assure we have the same coverage of information on the doc site.

Since Stencil automatically uses these files an generates documentation samples, it would be nice if we could keep these and use them to generate some of the doc site samples. That way, the samples are within the code base and can easily be referenced. A developer who is developing a component or functionality, has the ability to define usage easier if they can do so within the code base.

**Comment by DitwanP** [comment]
> I'm not sure I agree with removing these at this time.
> 
> @jcfranco what about where we are lacking coverage for some of these on the doc site? For example, there is no virtual element info on popover in the doc site.
> 
> If we remove some of these usage files I'm concerned we will be losing info on how to do some things.
> 
> IMO it would be better to leave these until we can assure we have the same coverage of information on the doc site.

So the plan was to go through the components on the doc site and improve coverage, fix descriptions, and make sure things are still accurate.
 
Maybe we just leave this for now until the doc site work is done, which is what I was thinking to do initially but wasn't sure if it mattered that much. 

>Since Stencil automatically uses these files an generates documentation samples, it would be nice if we could keep these and use them to generate some of the doc site samples. That way, the samples are within the code base and can easily be referenced. A developer who is developing a component or functionality, has the ability to define usage easier if they can do so within the code base.

I'm uncertain about the advantages here. It seems like the documentation site offers more detailed examples that often encompass most usage scenarios. While the codebase contains numerous usage files with minor differences, such as adding a property or two to a component, the documentation site could likely achieve the same effect with a toggle.

**Comment by jcfranco** [comment]
> what about where we are lacking coverage for some of these on the doc site? For example, there is no virtual element info on popover in the doc site.

Good point on removing usage files that don't have a counter part in the doc site. Can we come up with a list of _useful_ usage files that are missing from the doc site? I have a hunch it will be a small list. In any case, we can prioritize those items for future doc improvements.

> Maybe we just leave this for now until the doc site work is done, which is what I was thinking to do initially but wasn't sure if it mattered that much.

This seems like the best path forward. Once we know we've got proper coverage on the doc site, we should be good to remove usage files and possibly provide guidance on how to add/update doc examples that will get referenced in the doc site.

> I'm uncertain about the advantages here. It seems like the documentation site offers more detailed examples that often encompass most usage scenarios. While the codebase contains numerous usage files with minor differences, such as adding a property or two to a component, the documentation site could likely achieve the same effect with a toggle.

Agreed. For context, we are removing usage files for a couple of reasons:

1. we aim for the doc site to serve as definitive source of usage examples
2. currently, the doc site does not use/reference usage files
3. generated readmes offer incomplete documentation compared to what the doc site provides

@DitwanP @macandcheese LMK if I missed anything.

**Comment by DitwanP** [comment]
The list below Is what I've found for usage samples that might need to get recreated on the doc site, not sure if they all need to so @macandcheese feel free to LMK what we should exclude if any.

- **Button**
  - Internals sample?
- **Input**
  - Native Events?
- **Label**
  - Browser Caveat?
- **Modal**
  - Before close
- **Popover**
  - Virtual
- **Sheet**
  - Before close
- **Shell Panel**
  - With custom element?
- **Tooltip**
  - Virtual

**Comment by driskull** [comment]
We should add the virtual element doc for popover and tooltip.

**Comment by jcfranco** [comment]
Thanks y'all!

I agree with @macandcheese and @driskull's recommendations.

**Comment by DitwanP** [comment]
The usage snippets that were not previously represented on the doc site has now been added, everything else was already covered by the existing samples.

**Comment by benelan** [comment]
This is going the opposite direction of what I had hoped we would do :sob:. 

It would be great if we could have the usage examples source of truth in the monorepo right next to the source code and API reference. 

When I discussed this with @macandcheese before it sounded like there were just some formatting issues/inconsistencies that prevented him from being able to parse the usage example strings and use them in the doc site. 

I think we should be standardizing the format of the usage examples, and from there I could write a simple parser to grab the examples, their descriptions, etc. for use in the doc site.

Speaking for myself, I'm way more likely to learn from and contribute to usage examples if they are in the monorepo, rather than hidden behind a VPN.

Additionally, people may be using the usage fields of docsjson for something (although we don't have it documented so removing it wouldn't be a breaking change)

https://cdn.jsdelivr.net/npm/@esri/calcite-components@2.8.3/dist/extras/docs-json.json

**Review by alisonailea — APPROVED** [review]

**Review by jcfranco — APPROVED** [review]

**Pull request merged**
