### PR TITLE
build(deps): bump storybook to v8

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

Bump Storybook to v8.

### Notes

* Upgrades deps to the latest version
* Removes unused/unsupported deps
* Sets up interactions addon
* Replaces the no-longer-supported `@storybook/addon-knobs` with fake ones to clean up and restore (`@storybook/addon-controls`) in a follow-up PR
* Replaces RTL and theming addons with supported versions.
* Removes "no test" and "test only" story filters as dynamic set ups are no longer required.
* Drops unnecessary `keydown` intercepting since new shortcut to search stories is no longer `/` (now `CMD/CTRL + K`)
* Sorts all icon options for snapshot consistency
* Updates conventions doc
* Removes no longer used component readme imports
* Drops `_NoTest` stories except for all-variant stories for tile and tile-group 
* Keeps the `_TestOnly` story suffix until the #7180 lands.

### CODE REVIEW

**Comment by jcfranco** [comment]
**Screenshot test notes:**

* stories using the first icon are now consistent
* some `shell` and `slide` and `flow` stories are now rendering accurately
* `text-area` stories are displaying wider, not sure if this is expected or not

**Comment by driskull** [comment]
`screenshot-tests:preview` is the replacement script for `docs:preview` correct?

**Review by driskull — APPROVED** [review]
Looks awesome. Tested it out and its much faster than previous versions.

**Comment by jcfranco** [comment]
> screenshot-tests:preview is the replacement script for docs:preview correct?

You are correct, sir. Updated [here](https://github.com/Esri/calcite-design-system/pull/8944).

**Pull request merged**
