### PR TITLE
chore(sort-handle): add messages

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #7537

## Summary

- add messages for translation

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
✨🧶✨

**Comment by driskull** [comment]
@geospatialem could you review the strings?

**Comment by driskull** [comment]
@geospatialem instead of using direction like `up/down/top/bottom`, how about:

- `forward/backward/start/end`
- `ahead/behind/start/end`

Thoughts?

It might be safer incase we ever need to reorder horizontally.

**Comment by driskull** [comment]
Example UI for context

image

**Review by geospatialem — APPROVED** [review]
LGTM! 💪🏻 

> @geospatialem instead of using direction like up/down/top/bottom, would it be better to use non directional terms?
> 
> forward/backward/start/end
> ahead/behind/start/end
> next/previous/first/last

@driskull _Think_ its okay to leave as-is, while we could have more coverage and consistency, this seems a bit more confusing to list "Move to start" / "Move to bottom". If we do move to horizontal sorting we could consider alternative approaches in the future.

**Pull request merged**
