### PR TITLE
fix(input-time-zone): fix city translations

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

Updates translations for `Asia/Calcutta` and `Antarctica/DumontDUrville` IANA time zones.

### CODE REVIEW

**Comment by jcfranco** [comment]
cc @richieCarmichael

**Comment by richiecarmichael** [comment]
Also:
`"America/Bahia_Banderas": "Bahia Banderas"` -> `"Bahia de Banderas"`

**Review by anveshmekala — APPROVED** [review]
🕙

**Comment by jcfranco** [comment]
> Also, what is the convention on accents in English names? For example, "Tucuman" is referred to as "Tucumán" in Wikipedia and Google Maps.
> 
> * Tucuman -> Tucumán
> * Merida -> Mérida
> * Zurich -> Zürich

Excellent question. @annierm18 can you guide us on this one? cc @anveshmekala

**Comment by jcfranco** [comment]
Went with the accentless version for the time being.

**Pull request merged**
