### PR TITLE
chore(text-area): add new string for when character length is `tooShort`

### PR DESCRIPTION
**Pull request by Elijbet**
**Related Issue:** #10970

## Summary
Check in new string.

### CODE REVIEW

**Review by benelan — APPROVED** [review]
:+1:

**Comment by jcfranco** [comment]
@Elijbet Why is this separate from https://github.com/Esri/calcite-design-system/pull/10970?

**Comment by Elijbet** [comment]
> @Elijbet Why is this separate from #10970?

From what I understood I could check in new strings and request translations while that PR is being reviewed.

**Comment by jcfranco** [comment]
Gotcha. We might not need to submit this separately since #10970 looks close.

**Comment by Elijbet** [comment]
> Gotcha. We might not need to submit this separately since #10970 looks close.

Merging this in per: https://github.com/Esri/calcite-design-system/pull/10970#discussion_r1889383200

**Pull request merged**
