### PR TITLE
fix(panel, flow-item): remove overflow rule

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #8028

## Summary
Attempt to fix the clipping of action-menu in Panel and FlowItem.
This draft adds a test demo to approximate one of the use cases where the issue is appearing.

I could use some help testing if this update breaks other stuff.
cc @geospatialem

### CODE REVIEW

**Comment by asangma** [comment]
Thanks @jcfranco !

**Review by geospatialem — COMMENTED** [review]
This LGTM with all Windows browsers (Chrome, FF, and Edge). Did a few more edge cases around `flow`, `panel`, and `flow-item` and didn't observe anything out of the ordinary.

That said, defer to the designers and devs on final snapshot changes and code respectively.

**Comment by asangma** [comment]
Ready for review.

**Comment by geospatialem** [comment]
@asangma Summarizing our Teams discussion below:

To ensure the above fix does not impact functionality, if adopted earlier into the milestone, we could ask teams to perform testing to get more 👀 on this as well. Alan and I performed some initial tests, but we think the more testing and folks to look at this - the better. As a result will add as another testing mechanism for our November breaking change release (on our internal breaking change page).

cc: @jcfranco @brittneytewks

**Comment by jcfranco** [comment]
@asangma belated thanks for helping us out with this one! 💪🏼

@geospatialem thank you for testing and the summary above. 

There does seem to be [one screenshot test](https://www.chromatic.com/test?appId=6266d45509d7eb004aa254fb&id=65396fc4d4b83f4387e5532c) affected by this change. @driskull @SkyeSeitz @ashetland could you take a closer look? If everything looks good, we can proceed with @geospatialem’s recommendation to install early for additional testing.

**Comment by driskull** [comment]
I think that test looks good. The content is still scrollable and the FAB is positioned correctly.

**Comment by ashetland** [comment]
> I think that test looks good. The content is still scrollable and the FAB is positioned correctly.

Awesome

**Review by jcfranco — APPROVED** [review]
Code LGTM! 

@asangma Could you make sure to add a screenshot test before merging? 

@driskull @ashetland thanks for taking a look.

**Comment by driskull** [comment]
Maybe we should create an issue to add more information for each screenshot test? Maybe we could put a paragraph of text for verifying a screenshot for each test?

Not sure where but maybe within the screenshot might be best so designers can see the information as well?

**Comment by jcfranco** [comment]
@driskull I think we could do an audit on all tests to see which ones need additional info. The story title should indicate what the screenshot test entails. Some stories could benefit from additional info within the story. We do this for the responsive stories and I think it's pretty helpful for composite or complex screenshot tests.

**Comment by jcfranco** [comment]
I'm going to go ahead and merge this for early testing. 

@asangma @driskull can you team up and make sure we add a screenshot test for this?

**Comment by MukeZ** [comment]
Hey guys, after updating to this version, the scroll bar gets disabled if the panel height is too long. It was working with version 1.10.0. Now, I need to add a function to automatically set the max-height of the panel based on the window's height and add 'overflow-y: auto;' to my custom CSS

**Pull request merged**
