### PR TITLE
feat(tab-nav): add support for built-in translations

### PR DESCRIPTION
**Pull request by Elijbet**
**Related Issue:** #6689 

## Summary
This PR will add built-in translation support for the `tab-nav` component.
Users can now leverage the `messageOverrides` property to override default translations for the supported locale.

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]
🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐
🌐🗣🌐🌐🌐🗣🌐🗣🗣🗣🌐🌐🗣🗣🗣🌐🗣🗣🗣🗣🌐🗣🌐
🌐🗣🗣🌐🌐🗣🌐🌐🗣🌐🌐🗣🌐🌐🌐🌐🗣🌐🌐🌐🌐🗣🌐
🌐🗣🌐🗣🌐🗣🌐🌐🗣🌐🌐🗣🌐🌐🌐🌐🗣🗣🗣🌐🌐🗣🌐
🌐🗣🌐🌐🗣🗣🌐🌐🗣🌐🌐🗣🌐🌐🌐🌐🗣🌐🌐🌐🌐🌐🌐
🌐🗣🌐🌐🌐🗣🌐🗣🗣🗣🌐🌐🗣🗣🗣🌐🗣🗣🗣🗣🌐🗣🌐
🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐

**Review by anveshmekala — COMMENTED** [review]
I don't see that messages being used in the component. Is this expected?

**Comment by jcfranco** [comment]
@anveshmekala Good catch. 🎣 That would explain the test failures. 

@Elijbet Can you wire up `messages` to the component's rendering?

**Comment by Elijbet** [comment]
> @anveshmekala Good catch. 🎣 That would explain the test failures.
> 
> @Elijbet Can you wire up `messages` to the component's rendering?

The only message bundles added here https://github.com/Esri/calcite-design-system/pull/7914 were `[next/previous]TabTitles` and at this time the action buttons are not added to the main, that's the reason the messages aren't wired. This PR was awaiting the responsive tabs enhancement, which would have brought in the functioning scroll buttons. Looks like that's the reason I kept it in the draft state initially.

**Comment by jcfranco** [comment]
Merged this into https://github.com/Esri/calcite-design-system/pull/8616 and closing in favor of it. Thanks @Elijbet!

**Pull request closed without merging**
