### PR TITLE
chore(linting): wire up px-to-rem linting rule

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

Sets up linting rule to automatically convert px-to-rem on commit. This should help with sizing when the browser font size is modified.

### CODE REVIEW

**Review by anveshmekala — APPROVED** [review]
🥇 🥇 🥇

**Comment by anveshmekala** [comment]
Nitpick: can you add PR description.

**Comment by alisonailea** [comment]
To align with this change we should review design tokens as well. Not all platforms use rems but we could convert tokens at SCSS generation to REMs if that is preferable.

**Comment by jcfranco** [comment]
Closing until we confirm this is something we want to pursue.

**Pull request closed without merging**
