### PR TITLE
refactor(pick-list, pick-list-group, pick-list-item, value-list, value-list-group, value-list-item)!: Remove deprecated components.

### PR DESCRIPTION
**Pull request by aPreciado88**
**Related Issues:** 

[#9296](https://github.com/Esri/calcite-design-system/issues/9296)
[#9297](https://github.com/Esri/calcite-design-system/issues/9297)

## Summary

Remove the following deprecated components:

- pick-list
- pick-list-group
- pick-list-item
- value-list
- value-list-group
- value-list-item

BREAKING CHANGE: Use the `List` component instead.

### CODE REVIEW

**Comment by aPreciado88** [comment]
@driskull I updated the title and description. Thanks for catching that!

**Comment by driskull** [comment]
Maybe the PR title can be shorted to:

fix(pick-list, pick-list-group, pick-list-item, value-list, value-list-group, value-list-item)!: Remove deprecated components.

And the breaking change description:

BREAKING CHANGE: The `list` component should be used instead of the following components:

**Review by driskull — APPROVED** [review]
LGTM! Should wait to merge until after the oct release wraps up.

**Comment by aPreciado88** [comment]
@ashetland @SkyeSeitz Could you please take a look at the chromatic build? It looks like they're false positives, but I want to confirm.

**Comment by ashetland** [comment]
Yep, just the usual set of false positives. 🍰

**Comment by jcfranco** [comment]
Can you move the `BREAKING CHANGE` footer to the end of the description? It needs to be placed at the bottom to adhere to the [conventional commits spec](https://www.conventionalcommits.org/en/v1.0.0/#summary):

```
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

**Comment by jcfranco** [comment]
> It might be refactor()!: but I don't think our changelog picks up refactors so maybe we should use fix()!:? cc @jcfranco

`refactor` is the appropriate type. The breaking changes will be reflected in the changelog (see [2.0.0 changelog](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/CHANGELOG.md#-breaking-changes) and [some](https://github.com/Esri/calcite-design-system/pull/8099) [example](https://github.com/Esri/calcite-design-system/pull/8217) [PRs](https://github.com/Esri/calcite-design-system/pull/8234)).

**Pull request merged**
