### PR TITLE
fix(action): Update transparent action styles

### PR DESCRIPTION
**Pull request by macandcheese**
**Related Issue:** #3834 

## Summary
cc @asangma @SkyeSeitz @ashetland

### CODE REVIEW

**Comment by SkyeSeitz** [comment]
Looking good! A few small notes before approving the rest of the snapshots..
* The active fg-3 background [goes away when loading=“true”](https://github.com/Esri/calcite-design-system/assets/29716057/d7301312-1f8e-4398-9cc1-151a5621b495)
* The loader not animating is a Storybook artifact, correct?
* Should the hover leave 1px top & bottom or can it fill the height of the container? 
hello world

* Same here?
Estuaries

* Super smol but there is corner radius mismatch here on all [dismissible popover](https://6266d45509d7eb004aa254fb-ufvywejadj.chromatic.com/?path=/story/components-popover--large-scale-layout-test-only ) scales (I think this is just for the test tho?)

Pasted Graphic 2

**Comment by macandcheese** [comment]
> Super smol but there is corner radius mismatch here on all [dismissible popover](https://6266d45509d7eb004aa254fb-ufvywejadj.chromatic.com/?path=/story/components-popover--large-scale-layout-test-only) scales

Nice catch! Should be unrelated to this PR though - could you open a new issue?

> Should the hover leave 1px top & bottom or can it fill the height of the container?
This is the current behavior, it might be resolved by https://github.com/Esri/calcite-design-system/issues/7538, could you add a +1 there?

For the "Estuaries" one that is not close to full-height, only Action elements are slotted and automatically stretched - that is slotted into the Dropdown trigger so isn't being stretched. I think this could be improved, but also something a user can adjust. Upcoming changes to Dropdown might resolve this by using a `reference-element` instead of user needing to slot a trigger inside Dropdown.

I'll take a look at the FG change in loading, can you confirm the behavior for this transparent mode and solid? Thanks!

**Comment by SkyeSeitz** [comment]
> I'll take a look at the FG change in loading, can you confirm the behavior for this transparent mode and solid? Thanks!

I would expect the transparent active Action to retain its fg-3 background when loading="true" as it does in solid. 

> This is the current behavior, it might be resolved by https://github.com/Esri/calcite-design-system/issues/7538, could you add a +1 there?

Added a +1 to https://github.com/Esri/calcite-design-system/issues/7538

> Nice catch! Should be unrelated to this PR though - could you open a new issue?

Good point - thought that was new to this build. Issue created ✅ https://github.com/Esri/calcite-design-system/issues/8208

**Review by jcfranco — APPROVED** [review]
Code changes LGTM! 🚀

**Pull request merged**
