### PR TITLE
fix(accordion-item): stretch slotted actions only

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #10731 

## Summary

This avoids unintentionally styling other actionable components and offers more flexibility.

**Note**: this changes styles to use explicit selectors instead of universal ones to improve maintainability.

### CODE REVIEW

**Comment by jcfranco** [comment]
Alternatively, we could also tweak `switch` (and similar ones), so that it centers when stretched vertically.

**Review by driskull — APPROVED** [review]
👍

**Comment by macandcheese** [comment]
> Alternatively, we could also tweak `switch` (and similar ones), so that it centers when stretched vertically.

This could be a nice fallback for all non-action elements. A user can always slot a div, unset styles - but I think center align is a more expected default than align-top?

**Comment by jcfranco** [comment]
@macandcheese Fortunately, slotted, non-action items are already centered, so no further changes needed! 🎉

**Pull request merged**
