### PR TITLE
fix(list-item): hide nested list items by default

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #9400

## Summary

- Hides nested/indented list items by default
- Removes unnecessary div

### CODE REVIEW

**Review by alisonailea — APPROVED** [review]
simplification! 🎉

**Review by jcfranco — APPROVED** [review]
Awesome! 📝

There doesn't seem to be any reported diffs in the Chromatic build. If missing, can you add a screenshot test?

**Comment by driskull** [comment]
> There doesn't seem to be any reported diffs in the Chromatic build. If missing, can you add a screenshot test?

I don't think a screenshot test would cover this. Its basically a flash of content.

**Comment by jcfranco** [comment]
Gotcha. Thanks for clarifying!

**Pull request merged**
