### PR TITLE
fix(dialog): update content background color to match modal

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #10809 

## Summary

Updates `dialog`’s content background color to be consistent with `modal`, easing the team’s migration efforts.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍

**Comment by ashetland** [comment]
All the diffs were false positives. I did not see a diff for Dialog, however. With the color change, there should be one, right?

**Comment by jcfranco** [comment]
@ashetland Not sure why Chromatic didn't catch it. 🤔❓

**Comment by jcfranco** [comment]
I'll run another screenshot build to see if it catches it.

**Review by ashetland — APPROVED** [review]
Chromatic still isn't catching the diff for some reason, but we're good to go. All the other diffs were false positives.

**Pull request merged**
