### PR TITLE
build(deps)!: bump Stencil to v4

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #7861 

## Summary

Bumps Stencil to v4.

### Noteworthy changes

* add `components.d.ts` to source control per [Stencil recommendation](https://stenciljs.com/docs/typed-components)
* add workaround for JSX imports not matching what Stencil React output target expects
* dropped workaround for https://github.com/Esri/calcite-design-system/issues/6696 (fixed in v4)
* drop obsolete tree-shaking patch (#5233) (fixed in v4)
* skips additional locales that are showing formatting differences between test/node and browser environments
* updates `volta` and `engines` fields from `eslint-plugin-calcite-components`' `package.json` to match other packages
* dep changes:
  * bumps `@typescript-eslint`†, `angular`†, `jest`†, `puppeteer`, `typescript` to latest († and related deps)
  * removed unused `@stencil/state-tunnel`
  * replaced `@stencil/postcss` with `@stencil-community/postcss`
  * added missing `globby` and `jsdom`
  * override `@jest/transform` to ensure node types match

BREAKING CHANGE: We are treating this core version bump as a precautionary measure, particularly due to its potential impact on projects using `calcite-components` and Stencil.

### CODE REVIEW

**Review by benelan — APPROVED** [review]
Awesome! [This patch](https://github.com/Esri/calcite-design-system/blob/jcfranco/7861-bump-stencil-to-v4/packages/calcite-components-angular/support/stencilDoubleBuildTypesWorkaround.sh) can also be removed now that we committed `components.d.ts`.

Otherwise LGTM!

**Comment by jcfranco** [comment]
> Awesome! [This patch](https://github.com/Esri/calcite-design-system/blob/jcfranco/7861-bump-stencil-to-v4/packages/calcite-components-angular/support/stencilDoubleBuildTypesWorkaround.sh) can also be removed now that we committed components.d.ts.

Noice. I'll remove that patch in a follow-up PR.

**Comment by jcfranco** [comment]
Skipping screenshots before installing as last change was specific to E2E tests and previous screenshot tests were ✅.

**Review by driskull — COMMENTED** [review]
👍 Nice!

**Comment by ffaubry** [comment]
@jcfranco I'm adding question here even if this PR is merged. Let me know there is a better place.

- You are using a fix version for stencil core. Why not using ^4.7.1? 
- You move the angular wrapper to 17. What's your thoughts about angular 16?


BTW, we stopped using ts-node and we are using tsx. Faster IMO.

**Comment by jcfranco** [comment]
> You are using a fix version for stencil core. Why not using ^4.7.1?

IIRC, mainly to ensure a consistent test/debug environment and to reduce merge conflicts in `package-lock.json`.

> You move the angular wrapper to 17. What's your thoughts about angular 16?

We thought we would use the latest since we were updating other dependencies, but we could downgrade to v16. @benelan WDYT?

> BTW, we stopped using ts-node and we are using tsx. Faster IMO.

Noted. We will look into this and possibly make the switch too.

**Pull request merged**
