### PR TITLE
feat(list): add filterPredicate property to handle custom filtering

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #6544

## Summary

- add `filterPredicate` property.
  - `filterPredicate: (item: ListItem["el"]) => boolean;`
- add e2e test
- cleanup 

## Example

```js
list.filterPredicate = (item) => {
  if (list.filterText === "all") {
    return true;
  }

  return item.value === "item2";
};
```

### CODE REVIEW

**Review by benelan — APPROVED** [review]
Nice! Do you think it would be helpful to add an example of `filterPredicate` to the component's demos page? We usually use a story but that doesn't work for javascript-only features yet.

**Comment by driskull** [comment]
> Nice! Do you think it would be helpful to add an example of filterPredicate to the component's demos page? We usually use a story but that doesn't work for javascript-only features yet.

What about an `@example` in jsdoc? Would that work? cc @geospatialem

**Comment by driskull** [comment]
@geospatialem @benelan does the example jsdoc look ok to you? Should we add more description to the property?

**Comment by geospatialem** [comment]
> @geospatialem @benelan does the example jsdoc look ok to you? Should we add more description to the property?

I don't believe the `@example` will show up in our docs, but @macandcheese is this something we could add to our 3.0 doc preview branch?

**Comment by driskull** [comment]
Going to merge this. We can make doc improvements in follow ups.

**Comment by benelan** [comment]
Yeah LGTM! We can add the example before the doc site supports the tag like we've been doing with the custom mdn tag.

**Comment by macandcheese** [comment]
> > @geospatialem @benelan does the example jsdoc look ok to you? Should we add more description to the property?
> 
> I don't believe the `@example` will show up in our docs, but @macandcheese is this something we could add to our 3.0 doc preview branch?

We don't render `@example` as they won't fit into a Table layout. We could look to display them elsewhere on a component page, or add extra, mdx-based documentation in the component pages.

**Pull request merged**
