### PR TITLE
fix(checkbox): ensure that checkbox outline shows in high-contrast

### PR DESCRIPTION
**Pull request by mpriour**
**Related Issue:** #10537 

## Summary
Adds the `outline-none` tailwind utility class that only shows in Windows high-contrast mode

### CODE REVIEW

**Review by jcfranco — APPROVED** [review]

**Comment by jcfranco** [comment]
Thanks for taking this on, @mpriour! ✨💪 :octocat: ✨

**Comment by jcfranco** [comment]
@mpriour I did a quick test and noticed that in high-contrast mode, the focus outline is always displayed, which makes it difficult to distinguish the currently focused checkbox. Could you confirm if this is intentional? If not, you might want to adjust the box shadow, since it’s used to create the checkbox border.

**Comment by mpriour** [comment]
That's odd. When I checked it there was a separate focus ring (about 2px out).
I can check again soon.

**Comment by jcfranco** [comment]
@mpriour We've [migrated to Lit](https://github.com/Esri/calcite-design-system/issues/10310) since this PR was opened. I took a stab at this over at https://github.com/Esri/calcite-design-system/pull/10823. Could you review and test it out?

**Comment by mpriour** [comment]
Sure thing!

**Pull request closed without merging**
