### PR TITLE
ci: compile estimate totals per milestone

### PR DESCRIPTION
**Pull request by benelan**
**Related Issue:** #8359

## Summary

Add an action that creates a spreadsheet and JSON file with the total estimates per milestone. The action runs when an issue closes and can be manually dispatched. The files are saved as artifacts in the workflow run. I'll add a wiki page about running the workflow and retrieving the data once it's live.

It might be because I'm a GraphQL noob, but Monday's API reference was not very helpful. I can give the integration another try if this is not ergonomic enough.

### CODE REVIEW

**Review by geospatialem — COMMENTED** [review]
Awesome! 🏆 

Code-wise will defer approval to @jcfranco, but in initial sleuthing this looks great! Wondering if there are limitations that should be mentioned here as well, it looks like we can only run on up to 100 milestones and 100 issues for each milestone. Wondering if that could pose a problem, in particular around the 100 milestones since they could be open or closed. WDYT?

**Comment by benelan** [comment]
I'm paginating the issues so there is no limit. I could do the same for milestones, the downside being runs will take longer. You're the main consumer of this data so let me know how many milestones should be included and if you'd like any additional columns.

**Comment by geospatialem** [comment]
> I'm paginating the issues so there is no limit. I could do the same for milestones, the downside being runs will take longer. You're the main consumer of this data so let me know how many milestones should be included and if you'd like any additional columns.

No worries, it seems like a good approach and we can re-evaluate in the future if needed. 💪🏻

**Review by jcfranco — APPROVED** [review]
📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉
📉📈📉📉📉📈📉📉📈📈📉📉📈📈📈📉📉📈📈📈📉📈📈📈📈📉📈📉
📉📈📈📉📉📈📉📈📉📉📈📉📉📈📉📉📈📉📉📉📉📈📉📉📉📉📈📉
📉📈📉📈📉📈📉📈📉📉📈📉📉📈📉📉📈📉📉📉📉📈📈📈📉📉📈📉
📉📈📉📉📈📈📉📈📉📉📈📉📉📈📉📉📈📉📉📉📉📈📉📉📉📉📉📉
📉📈📉📉📉📈📉📉📈📈📉📉📈📈📈📉📉📈📈📈📉📈📈📈📈📉📈📉
📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉📉

**Pull request merged**
