### PR TITLE
build(deps): bump React deps to v18

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

🤜💥🤛

### CODE REVIEW

**Review by benelan — APPROVED** [review]
:+1:

**Review by benelan — APPROVED** [review]
:+1:

**Comment by benelan** [comment]
@jcfranco I just noticed that there are some errors building the react wrapper, do you want me to take a look?

```
Error: @esri/calcite-components-react:build: src/react-component-lib/createOverlayComponent.tsx(140,13): error TS2322: Type 'PropsWithoutRef<Props> & { forwardedRef: ForwardedRef<OverlayType>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Overlay> & Readonly<Props>'.
  Type 'PropsWithoutRef<Props> & { forwardedRef: ForwardedRef<OverlayType>; }' is not assignable to type 'Readonly<Props>'.

Error: @esri/calcite-components-react:build: src/react-component-lib/utils/index.tsx(40,27): error TS2345: Argument of type '{ (props: StencilReactExternalProps<PropType, ElementType>, ref: StencilReactForwardedRef<ElementType>): React.JSX.Element; displayName: string; }' is not assignable to parameter of type 'ForwardRefRenderFunction<ElementType, PropsWithoutRef<StencilReactExternalProps<PropType, ElementType>>>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'PropsWithoutRef<StencilReactExternalProps<PropType, ElementType>>' is not assignable to type 'StencilReactExternalProps<PropType, ElementType>'.
      Type 'Omit<HTMLAttributes<ElementType>, "style"> & StyleReactProps' is not assignable to type 'StencilReactExternalProps<PropType, ElementType>'.
        Type 'Omit<HTMLAttributes<ElementType>, "style"> & StyleReactProps' is not assignable to type 'PropType'.
          'PropType' could be instantiated with an arbitrary type which could be unrelated to 'Omit<HTMLAttributes<ElementType>, "style"> & StyleReactProps'.
```

**Comment by jcfranco** [comment]
Thanks for testing, @benelan! Tested w/ #10482 and confirmed that these dep bumps will not be an issue after that lands.

**Pull request merged**
