### PR TITLE
test(panel, flow-item): add scale control to simple stories

### PR DESCRIPTION
**Pull request by DitwanP**
**Related Issue:** #6980 

## Summary
Adding scale control to the simple stories on storybook

### CODE REVIEW

**Review by driskull — APPROVED** [review]
👍 Looks good @DitwanP ⭐

**Review by geospatialem — COMMENTED** [review]
@DitwanP Since the change relates to Storybook and not the code base, could you modify the [convention type](https://github.com/Esri/calcite-design-system/blob/dev/CONTRIBUTING.md#convention-type) from `feat` to `chore` or another type as you see fit?

**Comment by driskull** [comment]
It should probably be `test(panel, flow-item): add scale control to simple stories #9747`

**Comment by driskull** [comment]
@DitwanP seeing the following TS errors on these two stories:

- Property 'scale' does not exist on type 'FlowItemStoryArgs'.
- Property 'scale' does not exist on type 'PanelStoryArgs'.

can you open a PR to fix?

Scale should be added here:

```ts
 interface PanelStoryArgs
  extends Pick<
    Panel,
    "closed" | "disabled" | "closable" | "collapsed" | "collapsible" | "collapseDirection" | "loading"
  > {
  heightScale: string;
}
```

Can you make sure that your IDE is reporting the error?

**Pull request merged**
