### PR TITLE
fix(stepper-item): remove delay in highlighting item

### PR DESCRIPTION
**Pull request by josercarcamo**
**Related Issue:** #6482

## Summary
Removed delay in highlighting a stepper item.

### CODE REVIEW

**Review by driskull — APPROVED** [review]
This looks good. I wonder if the animation is for something? We could try adjusting the animation to only apply to whatever the animation is for instead of "all" which it likely is doing now.

**Comment by ashetland** [comment]
I took a looky look and I'm okay with losing the transition effect. The fade-in was pretty subtle and removing it makes this feel more snappy.

**Comment by ashetland** [comment]
Just noticed that in `layout="vertical"` the transition effect looks like it's still there.

**Comment by SkyeSeitz** [comment]
> This does remove the transition effect for the step bar highlights on hover. I'm not opposed to this change but let's run it by @ashetland and @SkyeSeitz. We can also maintain that and do what @driskull mentioned and scope the removal to just what affects the focus-ring outline.

I can't say I see a particular reason to remove the highlight bar animation as long as the focus ring effect gets adjusted. It is subtle enough, however, that we are not losing much if it goes away.

**Comment by jcfranco** [comment]
Does anyone recall what `duration-150` is supposed to target? That util is applied, but there's no explicit transition prop, so all props participate in the transition (see [example](https://codepen.io/jcfranco/pen/bGJoMRQ)).

**Comment by SkyeSeitz** [comment]
I think we are safe to move forward with removing the highlight bar animation. Thanks, y'all 👍🏽

**Comment by jcfranco** [comment]
@macandcheese @SkyeSeitz Thanks for confirming. I think this means we can drop all transitions (duration) from `stepper-item` then. We can do this in a separate PR.

**Pull request merged**
